/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class Base_Datos_Personal_Tabla extends javax.swing.JFrame {

    /**
     * Creates new form Base_Datos_Personal_Tabla
     */
    public Base_Datos_Personal_Tabla() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
        DefaultTableModel modelo = new DefaultTableModel();
        Tabla1.setModel(modelo);
        
        PreparedStatement ps = null;
        ResultSet resultado1 = null; 
        Conexion conn = new Conexion();
        Connection con =conn.getConexion();
        
       
        
        String sql = "SELECT Numero_de_Empleado, Nombre, Apellidos, Fecha_de_Nacimiento, CURP, RFC, Sueldo_bruto, Puesto, Sucursal, Fecha_de_Ingreso FROM personal"; 
        
        ps = con.prepareStatement(sql);
        resultado1=ps.executeQuery();
         
        ResultSetMetaData rsMd = (ResultSetMetaData)resultado1.getMetaData();
        int cantidadColumnas = rsMd.getColumnCount();
        
        modelo.addColumn("Numero_Empleado");
        modelo.addColumn("Nombre"); 
        modelo.addColumn("Apellido");
        modelo.addColumn("Fecha_de_Nacimiento");
        modelo.addColumn("CURP");
        modelo.addColumn("RFC");
        modelo.addColumn("Sueldo bruto");
        modelo.addColumn("Puesto");
        modelo.addColumn("Sucursal");
        modelo.addColumn("Fecha de Ingreso");

        
        
        
        
        
        
        while(resultado1.next()){
                Object[]  filas = new Object[cantidadColumnas];
                for(int i=0; i<cantidadColumnas; i++){
                filas[i] = resultado1.getObject(i+1);
            }
                modelo.addRow(filas);
                
            }

        
        
        
        }catch(SQLException error){
         System.out.println("Error3");
         System.err.println(error.toString());
        }
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Número de Empleado", "Nombre", "Apellidos", "Fecha de Nacimiento", "CURP", "RFC", "Sueldo bruto", "Puesto", "Sucursal", "Fecha de Ingreso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Consulta Personal de la Empresa");

        jButton1.setText("Eliminar Selección");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jButton1)))
                        .addGap(0, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton eliminar base de datos
        Conexion conn = new Conexion();
        Connection con =conn.getConexion();
        int fila = Tabla1.getSelectedRow();
        String valor = Tabla1.getValueAt(fila,0).toString();
        
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la información? \n Esta acción no se puede deshacer y LA INFORMACIÓN SERÁ BORRADA PERMANENTEMENTE ");
        if (confirmar==JOptionPane.YES_OPTION & fila>=0){
            
            try{
                PreparedStatement pps= con.prepareStatement("DELETE FROM personal WHERE Numero_de_Empleado='" + valor +"'");
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Se borró con éxito la información de la base de datos");
            }catch(SQLException error){
                JOptionPane.showMessageDialog(null, "Se produjo un error");
                System.out.println("Error04");
            }
        }else if(confirmar==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "No se realizaron cambios dentro de la base de datos");
        }else if(confirmar ==JOptionPane.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null, "No se realizaron cambios dentro de la base de datos");
        }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base_Datos_Personal_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base_Datos_Personal_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base_Datos_Personal_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base_Datos_Personal_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base_Datos_Personal_Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
